### PR TITLE
fixes #43

### LINKED ISSUE #43: Error
I have an Error when i pass to cake 3.1 

 Error: Unsupported operand types 
File /var/www/timesheets/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FlashHelper.php 
Line: 55

### PR DESCRIPTION
**Pull request by makamo**
change += to array_merge()

### CODE REVIEW

**Comment by ADmad** [comment]
Exactly how would one reproduce this error?

**Comment by makamo** [comment]
I just pass my project form cake 3.0 to 3.1

**Comment by dereuromark** [comment]
All keys should be strings, so I doubt that this fixes anything.
Please make an example as requested before.

**Comment by ADmad** [comment]
Value for `params` key is supposed to be always an associative array so the line you are changing should never generate an error. Simply switching from cake 3.0 to 3.1 does not generate any error as you claim.

Closing as the error is most likely being generated due to your app code. If you still the issue is with plugin's code please provide a test case or example code to reproduce the issue.

**Pull request closed without merging**
