### PR TITLE
Fix Tests for refactored TwigView

### PR DESCRIPTION
**Pull request by julianpollmann**
## Description
Fix Tests for MissingPluginException of TwigView.

### CODE REVIEW

**Comment by dereuromark** [comment]
Do we need up up any constraints here? Like bake ^2.1 ?

**Comment by julianpollmann** [comment]
Worked also with Bake 2.0, but I bumped the Versions

**Comment by dereuromark** [comment]
Are we ready to release RC or stable?

**Comment by dereuromark** [comment]
Also, we seem to be 55 behind master
I wonder if any of those should be merged into upstream.

**Comment by ADmad** [comment]
@dereuromark I have cherry-picked/re-implemented any bugfixes/enhancements from master to this Cake 4 branch. Given the divergence in code simple merge isn't feasible.

**Pull request merged**
