### PR TITLE
add date.css to examples

### PR DESCRIPTION
**Pull request by ayman-alkom**

### CODE REVIEW

**Comment by lorenzo** [comment]
What does this change?

**Comment by dereuromark** [comment]
@ayman-alkom It helps to provide a before/after screenshot comparison.

**Comment by ayman-alkom** [comment]
In fact I think that this PR is not necessary, it is just about setting the widths of the date input select items, in addition to some media query, witch can any one do in his own way.

**Comment by ayman-alkom** [comment]
@dereuromark this the after/before you mentioned
untitled

**Pull request closed without merging**
