### PR TITLE
Use newer, non-deprecated method

### PR DESCRIPTION
**Pull request by jonlachmann**
Use the newer getParam instead of older direct access of controller from view.

## Description
Use the newer getParam instead of older direct access of controller from view.

## Summarize
Just changed the two occurences in the file default.ctp

## Benefits
No deprecation warnings when changed.

### CODE REVIEW

**Comment by ADmad** [comment]
In the related issue you mentioned there were more such occurrences?

**Comment by dereuromark** [comment]
Can you please also fix the missing brackets around 

    if (isset($this->Flash))

seems like someone coded a bit dirty and the code sniffer doesnt find these things.

**Comment by jonlachmann** [comment]
> Can you please also fix the missing brackets around
> 
> ```
> if (isset($this->Flash))
> ```
> seems like someone coded a bit dirty and the code sniffer doesnt find these things.

How should it be? I am happy to add it in the pull request, if I can figure out how, but I'd rather do it right than wrong.

**Comment by dereuromark** [comment]
With brackets like the other if code. Without brackets is not allowed as per cs/psr2.

**Comment by jonlachmann** [comment]
Now I have fixed all occurrences of the deprecated method and also added the brackets, and managed to put them in the right branch to add them to the pull request.

**Pull request merged**
