### PR TITLE
add document variable @var to templates, representing View class

### PR DESCRIPTION
**Pull request by ayman-alkom**
I found this helps with the editors auto complete

### CODE REVIEW

**Comment by ADmad** [comment]
@jadb Are you okay with this? Personally not to happy having it in each file but meh.

**Comment by jadb** [comment]
@ADmad, it seems to help people on IDEs. They got added on core (specifically bake), so let's follow I say.

**Comment by ADmad** [comment]
Okay, then.

**Comment by ayman-alkom** [comment]
I have another pull request, and wait for this to be merged, I made a new branch but I had some problems then.

**Pull request merged**
