### PR TITLE
Update CI config

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
Ugghh.. The addition of `id` attribute to hidden inputs is causing a ton of test failures.

**Comment by ndm2** [comment]
Noice! Maybe we should add scheduled runs so that we get f'd in due time 😃

**Comment by ADmad** [comment]
Also if we add the ids it will fail with ` prefer-lowest`. Personally I wouldn't mind dropping that build.

**Comment by ndm2** [comment]
We could either drop the build, or like with the ARIA changes, implement adding the ID in a backwards compatible manner into the form helper, until we can bump the CakePHP version.

**Comment by ADmad** [comment]
> We could either drop the build, or like with the ARIA changes, implement adding the ID in a backwards compatible manner into the form helper, until we can bump the CakePHP version.

I have just ignored that failure for now.

**Pull request merged**
