### PR TITLE
Fixed Readme mistakes I made

### PR DESCRIPTION
**Pull request by Modicrumb**
Readme now has intended instructions. This is dealing with the directory structure changes I proposed.

### CODE REVIEW

**Comment by davidyell** [comment]
I think you should be suggesting using a symlink. Especially with Bower, as if I update my dependancy, I don't want to have to copy all the files again, I'd rather it just update automatically.

**Comment by Modicrumb** [comment]
Sounds like a better solution, my first idea was to create a gulp file that would move and update things automatically, but maybe a .bowerrc file would be better? http://stackoverflow.com/questions/19251931/symlink-or-copy-files-out-of-bower-component. Truthfully I am not too familiar with the idea of symlinking JavaScript/CSS assets. Is this done at the apache level? Got a link where I can read about it?

**Comment by ADmad** [comment]
@Modicrumb Just standard *nix symlinks (using `ln -s`).

**Comment by Modicrumb** [comment]
Yeah I think I will close this, it really isn't a great solution. Just the only one I thought of and stuck to. I do like the idea of keeping bootstrap assets in one folder in the pull request. The folder structure is a bit awkward with the fonts because they have to be put in the css folder for the original instructions to work. I can look into .bowerrc and symlinking instead. I feel it isn't an issue to warrant a lot of attention looking back at it since the brunt of the plug in is about facilitating writing mark up that is bootstrap compatible and people can set the layout up however they please. Thanks for the feedback.

**Pull request closed without merging**
