### PR TITLE
Flash helper edits so it can accept multiple flashes

### PR DESCRIPTION
**Pull request by Modicrumb**

### CODE REVIEW

**Comment by ADmad** [comment]
Support for multiple flashes is already available on `master` branch. 0.4 is a dev branch which is lagging behind master, you shouldn't be using it.

**Comment by ADmad** [comment]
Please open a PR against master branch if you think it has issue handing multiple flashes.

**Comment by dereuromark** [comment]
@ADmad I dont see it working yet for the latest release, though.

**Comment by ADmad** [comment]
Like I said a PR for master is welcome.

**Comment by dereuromark** [comment]
@Modicrumb Yes please please :)

**Comment by dereuromark** [comment]
Ah, I think a new release is missing
I am using tagged releases, currently `0.3.2` (not dev-master).
So please release a new version and then it hopefully all works out.

**Comment by ADmad** [comment]
It might be outdated but it's a feature branch which could be picked up again in the future. You should use `~3.0` as the master branch readme states.

**Comment by ADmad** [comment]
It might be outdated but it's a feature branch which could be picked up again in the future. You should use `~3.0` as the master branch readme states.

**Pull request closed without merging**
