### PR TITLE
valid html code when generating input errors

### PR DESCRIPTION
**Pull request by repher**
see #72

### CODE REVIEW

**Comment by ADmad** [comment]
You need to update related tests too.

**Comment by ADmad** [comment]
Can you post a screenshot for this? I hope using `<div>` doesn't make the message "stick" to other elements.

**Comment by repher** [comment]
Implementation with `<p>`:
screen shot 2015-07-10 at 16 46 44
screen shot 2015-07-10 at 16 48 09
Implementation with `<div>`:
screen shot 2015-07-10 at 16 46 16
screen shot 2015-07-10 at 16 48 37
(margin and list-style modified)

**Comment by repher** [comment]
there must be an error in assertHtml. The result on line 1025 for example ist just fine ... the class "help-block" ist there.

**Comment by ADmad** [comment]
> there must be an error in assertHtml

Nope :)  You must likely have multiple `div` keys in the assertion array.

**Comment by repher** [comment]
I don't get it. The result of Line 1025 is
```html
<div class="form-group required">
  <label class="control-label" for="title">Title</label>
  <input type="text" name="title" required="required" id="title" class="form-control">
  <div class="help-block">help text</div>
</div>
```
and therefore this should work:
```php
$result = $this->Form->input('title', ['help' => 'help text']);
$expected = [
    'div' => ['class' => 'form-group required'],
    'label' => ['class' => 'control-label', 'for' => 'title'],
    'Title',
    '/label',
    'input' => [
        'type' => 'text',
        'name' => 'title',
        'id' => 'title',
        'class' => 'form-control',
        'required' => 'required'
    ],
    'div' => ['class' => 'help-block'],
    'help text',
    '/div',
    '/div'
];
$this->assertHtml($expected, $result);
```
But it doesn't. Fails with:
```
1) BootstrapUI\Test\TestCase\View\Helper\FormHelperTest::testHelpText
Attribute did not match. Was expecting Attribute "class" == "help-block"
Failed asserting that false is true.

/Users/bernhard/Sites/bootstrap-ui/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:490
/Users/bernhard/Sites/bootstrap-ui/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:439
/Users/bernhard/Sites/bootstrap-ui/tests/TestCase/View/Helper/FormHelperTest.php:1026
``

**Comment by ADmad** [comment]
As I told you above your $expected array has 2 `div` key repeated, first in `'div' => ['class' => 'form-group required']` and second in `'div' => ['class' => 'help-block'],`. The second one overwrites the first. Wrap the second on in array `['div' => ['class' => 'help-block']]`.

**Comment by repher** [comment]
Thanks. I should have seen that. Time for some coffee... 😏

**Comment by ADmad** [comment]
Can you please squash the commits into one.

**Comment by repher** [comment]
Done. I guess... 😀

**Pull request merged**
