### PR TITLE
Update jquery version.

### LINKED ISSUE #351: collapse doesn't work with jQuery v3.5.0
TypeError: Cannot convert object to primitive value
while clicking to navbar-toggler button
I fixed it with an upgrade of JQuery to 3.5.1.
https://github.com/twbs/bootstrap/issues/30553
https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

Thank's

### PR DESCRIPTION
**Pull request by ADmad**
Closes #351

### CODE REVIEW

**Comment by ndm2** [comment]
Not sure how good Bootstrap and Popper are with regards to not breaking things in patch releases, but should we maybe consider dropping the `.lock` file, so that users can easily get the latest patch versions?

**Comment by ADmad** [comment]
Whatever you see fit. I don't use the css/js provideed through the plugin (nor any templates for that matter) so I don't care :slightly_smiling_face:.

**Comment by ndm2** [comment]
Well, I don't want to be the one who breaks everybody's stuff 😄

**Comment by ADmad** [comment]
Everyone lib maintainer does that sooner or later 😂.

**Comment by ndm2** [comment]
Yeah, well... let's leave that for another day 🙃 Maybe we can give it a try with for BS5.

**Pull request merged**
