### PR TITLE
Widget cleanup

### PR DESCRIPTION
**Pull request by ADmad**
Widgets no longer modify templates.

Existing master should be tagged as last 0.3 release and after merging this it should be tagged as 0.4 IMO.

### CODE REVIEW

**Comment by jadb** [comment]
Should we tag 0.4?

**Comment by ADmad** [comment]
Yup, I'm working on that.

**Comment by jadb** [comment]
:+1:

**Comment by ADmad** [comment]
I renamed the existing `0.4` branch to `style-guide` for whenever someone gets the time to follow up on it.

**Comment by jadb** [comment]
Very good idea - long year ahead ;)

**Pull request merged**
